spring.application.name=Project1
service.port=8086
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/employee_db
spring.datasource.username=postgres
spring.datasource.password=TIGER

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create